### ISSUE TITLE
Menu Navigation Missing

### ISSUE THREAD

**Issue by 22a** [22a/DUCSS-signup#5]
It is impossible to navigate in the app after a $state.go(), all navigation is missing.

http://forum.ionicframework.com/t/menu-button-missing-on-state-go-with-nightly-ionic/13403

**Comment by 22a** [comment]
maybe this will work, who knows, will fix in the morning. http://stackoverflow.com/questions/28221937/ionic-angular-1-3-missing-ion-nav-back-button-when-ion-side-menus-exist-insi

**Comment by c-brenn** [comment]
I can't navigate. HEKPHELP
